### ISSUE TITLE
"Handbuch des Münchner Stadtrats 2015" für Personenseiten nutzen?

### ISSUE THREAD

**Issue by konstin** [codeformunich/Ratsinformant#70]
Das [Handbuch des Münchner Stadtrats](http://www.muenchen.de/rathaus/Stadtpolitik/Der-Muenchner-Stadtrat/Handbuch-des-M-nchner-Stadtrats.html) enthält zu jedem Stadtrat und jedem Referent einen kurzen Text zusammen mit einem Bild. Der Text würde gut auf die Seiten der Stadtratsmitglieder passen. Dazu müsste aber geklärt werden, ob wir den Text von dort überhaupt übernehmen dürfen und wenn ja, wie man den (am besten automatisiert) aus dem pdf heraus bekommt.

**Comment by CatoTH** [comment]
Ich hab die Basisdaten jetzt übernommen, also Geburtstag/jahr, Geschlecht, und einen Teil der Beschreibung (der, der den persönlichen Hintergrund beschreibt). Fotos sind rechtlich mit ziemlicher Sicherheit nicht ohne weiteres möglich.
